fun main()
{
    println("Enter student's Enroll:")
    var enroll= readLine()
    println("Enter students name:")
    var name= readLine()
    println("Enter Students Branch:")
    var branch= readLine()
    println("Enter students class:")
    var Class = readLine()
    println("Enter students Batch:")
    var Batch= readLine()
    println("Enter students college:")
    var C= readLine()
    println("Enter students University name:")
    var n= readLine()
    println("Enter Students Age:")
    var age= readLine()

    println("Enter student's Enroll:$enroll")
    println("Enter students name:$name")
    println("Enter Students Branch:$branch")
    println("Enter students class:$Class")
    println("Enter students Batch:$Batch")
    println("Enter students college:$C")
    println("Enter students University name:$n")
    println("Enter Students Age:$age")
}